dataset:
  name: "data"
  format: "csv"
  delimiter: ","
  header: true

variables:
  service_week: 
    type: "string"
    description: "Service week in YYYY-MM format"
    time_variable: true
  service_date: 
    type: "string"
    description: "Date of service in YYYY-MM-DD format"
    time_variable: false
  betos_cd: 
    type: "string"
    description: "BETOS code for medical service"
    test_variable: true
  pos_cd: 
    type: "integer"
    description: "Place of service code"
    test_variable: true
  spec_cd: 
    type: "integer"
    description: "Specialty code of provider"
    test_variable: true
  paid_amount: 
    type: "float"
    description: "Amount paid for service"
    metric_variable: true  

metadata:
  source: "Healthcare Claims Data"
  author: "Your Name"
  created_on: "2025-02-08"
